---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: httpd
          image: httpd
      tolerations:
        - key: slave2
          value: intelliqit2
          operator: Equal
          effect: NoSchedule
...
          
      
